### ISSUE TITLE
SOGo version

### ISSUE THREAD

**Issue by grosbedos** [YunoHost-Apps/sogo_ynh#1]
Hi,

When i install SOGo, i have the version 3.2.6, is it normal ?
The description on github say 4.0.0.

Is it possible to have the 4.0.2 ? I'm searching to have this version to be able to search my entire mailbox (in all sub folder..)

Best regards

**Comment by grosbedos** [comment]
Ok, thanks !
Shame, because version 2.x has ability to search all folders, v4 too, but i have not see anything for the v3 ;)

Best regards

**Comment by Josue-T** [comment]
Ok, I didn't know. On debian buster there are a package with sogo 4.x here : https://packages.debian.org/buster/amd64/sogo

Mybe you can try to install this package but it' at your own risk. Installing a package from other debian version could make an instability on your system.

**Comment by grosbedos** [comment]
Hi,

Yes, thanks. I'm trying with the packages (sogo-sogo-common etc) from debian testing/sid (i'm on arm64), but it seems to not working for now, even on a clean debian install without yunohost ;)

Have a nice day

**Comment by EBII** [comment]
Hello @grosbedos @Josue-T 
i use the Sogo Nightly for stetch from offical repository to get Sogo 4 for yunhost with these steps! 
install sogo in yunohost => 3.2.6 official debian with yunohost like you do normally
connect with ssh admin@yuour_domain.tld  to get shell access
remove older sogo 
`sudo apt remove sogo && sudo apt autoremove ` (do not use --purge)

add sogo key like they write there:
https://sogo.nu/support/faq/how-to-install-nightly-sogo-versions-on-debian.html
`
sudo gpg --keyserver hkp://keys.gnupg.net --recv-key 0x810273C4
sudo gpg --armor --export 0x810273C4 | sudo apt-key add -
sudo apt-get update
`
add  sogo official nightly to your source list with this line :
`deb http://packages.inverse.ca/SOGo/nightly/4/debian/ stretch stretch` 

update:  `apt update`
install last version 
`sudo apt install sogo` 

keep already existing configuration file default=N is good !! 
and that's all ! 
go to your url set for the first install !!!

**Comment by grosbedos** [comment]
Thanks for your tutorial ;)

Unfortunately, i'm on arm64v8, and package from inverse.ca are just for amd64.
So i cannot follow your tutorial :(

Have a nice day !

**Comment by Josue-T** [comment]
@EBII, I know that a newest sogo version is available on the sogo repository, but as said this repository don't support all architecture.
