### ISSUE TITLE
Calendar sharing only works with the user chosen as admin (default permission is missing)

### ISSUE THREAD

**Issue by Vey** [YunoHost-Apps/sogo_ynh#2]
It may not be the way to go but this is the only way I found that worked. I hope it helps.

To be able to share calendars and contacts among users, edit sogo.conf:
```bash
$ sudo nano /etc/sogo/sogo.conf
```
add these lines:
```bash
 /* Default Calendar and Contacts Permissions */
 SOGoCalendarDefaultRoles = ("PublicViewer", "ConfidentialDAndTViewer", "PrivateDAndTViewer");
 SOGoContactsDefaultRoles = ("ObjectViewer");
```
restart sogo
```bash
sudo /etc/init.d/sogo restart
```

Cheers and thanks for your work

**Comment by Josue-T** [comment]
Hello,

Thanks for your issue. Can you just explain what did you try to do and what didn't work.

As I see the sogo documentation the recommended values are these : 
```
 /* Default Calendar and Contacts Permissions */
 SOGoCalendarDefaultRoles = ("PublicViewer", "ConfidentialDAndTViewer");
 SOGoContactsDefaultRoles = ("ObjectViewer");
```
Did you try it ?

And as it's written "Default", understand that it could be changed.

Anyway if you think that's the best option I can happily fix this in the package.

**Comment by Vey** [comment]
Use case is:
- user_1, user_2, user_3, user_4 are yunohost users
- sogo is installed in public mode
- user_1 is chosen as admin
- user_4 share a new calendar and adress book to the other users.
- user_1 can subscribe to the shared calendar and adress book but not user_2 or user_3

I removed the 'PrivateDAndTViewer' value you specified and it seems to keep working

**Comment by Josue-T** [comment]
Should be fixed in [the testing branch](https://github.com/YunoHost-Apps/sogo_ynh/tree/testing)
