### ISSUE TITLE
Error: Not allowed in state 1 when trying to send mails via Webmail

### ISSUE THREAD

**Issue by vsatmydynipnet** [YunoHost-Apps/sogo_ynh#20]
Fresh installed V11 Yunohost with all updates since today.

Everything works, also sending mails via Android, IOS, Outlook and Thunderbird. There is only the problem, if one sends e-mail via webmail/sogo then immediately "a red box telling me - not allowed in stage 1 - only with a close button" shows up.

Is there a workaround?

Thank yqu very much.

**Comment by gcollin** [comment]
I had the same issue (it used to work and suddenly I got the same error), so if someone is still interested, here is the fix:

sogo is using stunnel4 service to connect to smtp. stunnel4 must be start for sending messages to work.

to check if it's started, just login to your server, and do a 
systemctl status stunnel4

if it says it's not started, you can just 

systemctl start stunnel4
and check it has been started.

Then go to sogo website and try to send the message. It should work

To support restart, one can do the usual systemctl enable stunnel4

Hope this helps

**Comment by clicit** [comment]
@gcollin thanks that fixes the problem!

**Comment by 0utl4w** [comment]
Thx, had the same issue and you fixed it!

**Comment by Martin-bl** [comment]
Thank @gcollin  :smiley: 
The question : what is missing in Sogo package to fix it :upside_down_face:  ? 
thanks everybody for all your jobs

**Comment by gcollin** [comment]
I guess the installation script should ensure stunnel4 is enabled at boot and Sogo is dependent on stunnel4 in systemctl

**Comment by Pentaonia** [comment]
Hey all,

same issue for me (`not allowed in state 1`) after a server migration. But restarting either stunnel4 and/or Sogo does not fix the error. In the log the following error appears:

`[ERROR] <0x0x5574e5f91b30[SOGoMailer]> Could not connect to the SMTP server smtp://127.0.0.1:20001`

But from outside with a mail client I can send mails.

All the best and thanks in advance
Loubert

**Comment by Jeeboot** [comment]
Same issue on my side, due to the same reason probably since I just finished my server migration.
Any tip?
Thanks in advance :)
Jeeboot

**Comment by gcollin** [comment]
I don't have this issue so it's a bit difficult to help.
I assume postfix is running and listening at port 20001?

**Comment by Josue-T** [comment]
Closing as it should be fixed by #29
