### ISSUE TITLE
Mail folder sharing doesn't work

### ISSUE THREAD

**Issue by morta5** [YunoHost-Apps/sogo_ynh#21]
--- 

### Describe the bug

Using the option to allow other users to see the inbox(folder name > three dots > user rights) doesn't work

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 11.0.9.14
- I have access to my server: Through SSH | through the webadmin | direct access if necessary
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: I disabled something in postfix to make email delegation work (suggestion in issue #12 )
- Using, or trying to install package version/branch: 5.0.1~ynh1

### Steps to reproduce

   1. *Go to 'E-Mail.' as user1*
   2. *Click on the three dots of the folder*
   3. *Click on 'user rights'*
   4. *Add rights to user2*
   5. *Login as user2*
   6. *You won't see the folder from user1*

### Expected behavior

*I would expect to see the inbox of user1*

### Logs

Idk which logs are relevant, sorry

**Comment by GitBaer** [comment]
Same problem here. Any solution? Thank you.

**Comment by Josue-T** [comment]
Closing as there was some improvement about this in #29
