### ISSUE TITLE
Backup failure

### ISSUE THREAD

**Issue by Pentaonia** [YunoHost-Apps/sogo_ynh#26]
### Describe the bug

Sogo do not successfully backup because of a missing `'/etc/stunnel/sogo.conf'`.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.5 (stable)
- I have access to my server: *Through SSH | through the webadmin*
- Using, or trying to install package version/branch: 5.0.1~ynh2

### Steps to reproduce

Just try to backup the app via the web admin.

### Expected behavior

Successful backup.

### Logs

[HERE!](https://paste.yunohost.org/raw/gasunibutu)

**Comment by Salamandar** [comment]
That’s weird as this file should have been created by the app installation. It should contain something like:

```
[Smtp-Starttls]
client=yes
accept = __PORT_SMTP__
connect = 587

protocol = smtp
protocolAuthentication = plain
```
(with PORT_SMTP replaced by some port number specific to the app, probably 20001)

If it doesn’t exist, you might want to manually create it. You can get the port_smtp value by reading the file `/etc/yunohost/apps/sogo/settings.yml`. Once that’s done, you can backup the app again :)
