### ISSUE TITLE
sogo dav

### ISSUE THREAD

**Issue by ballinger** [YunoHost-Apps/sogo_ynh#34]
### Describe the bug

no dav connectivity to sogo if sogo is not in the visitor permission list

### Context

- Hardware: VPS
- YunoHost version: 12.0.3+202409101415 (unstable)
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: sogo nightly

### Steps to reproduce
not working: vanilla sogo install
working: sogo user added to visitor user rights

davx on android seems to be connecting to the ynh portal.

### Logs
dont see anything in the system logs, can try to fetch the davx log file if needed

**Comment by Josue-T** [comment]
Should be fixed by f662b29

**Comment by Josue-T** [comment]
Should be fixed on testing now
