### ISSUE TITLE
Multiple Mail Accounts?

### ISSUE THREAD

**Issue by bjesus** [YunoHost-Apps/sogo_ynh#5]
Hi! Thanks for packaging SOGo. I'm trying to use it with a mail account that's set outside of YunoHost, on a 3rd-party provider. The readme file lists one of the features as "Multiple Mail Accounts", but I can't seem to understand how to do it.

When I go to the Preferences page -> Mail -> IMAP Accounts, I can't seem to be able to add a new account to the list. Editing the current accout, which is my YunoHost account, also doesn't really work as all fields show disabled.

Is it possible to use SOGo on YunoHost with an external IMAP account (and CalDAV/CardDAV?)?

**Comment by TheNomad11** [comment]
Any news on this? Also trying to figure out how to add non-yunohost accounts. Does not seem to work

**Comment by Josue-T** [comment]
Closing this as I think is just linked to this: https://github.com/YunoHost-Apps/sogo_ynh/issues/8

On bullseye it should be fixed.
