### ISSUE TITLE
Non-ascii characters in calendar even names

### ISSUE THREAD

**Issue by kuba-orlik** [YunoHost-Apps/sogo_ynh#6]
Saving a name with, for example, Polish diacritics causes them to be replaced with `?`s. 

Example: Event name `Zażółć gęślą jaźń` ends up being saved as `Za?ó?? g??l? ja??`:

![image](https://user-images.githubusercontent.com/2697916/68996089-b2bb7380-0895-11ea-9910-1a49b7a5a1bf.png)

The issue does not appear in the SOGo demo site:

![image](https://user-images.githubusercontent.com/2697916/68996100-d54d8c80-0895-11ea-8d5a-dcd04c30038e.png)

Which seems to suggest that something is wrong with the setup on the yuno's side

**Comment by MakaryGo** [comment]
Same with contact names, all non-ASCII characters are replaced with `?`

**Comment by Josue-T** [comment]
On my side I also had some issues with non ascii char. The solution was to move all table to `utf8mb4_general_ci` collation.

You can do it with phpmyadmin (ynh app) on sogo db >  Operations > Interclassement >   `utf8mb4_general_ci`  and enable the 2 checkbox bellow.
